"""add email settings

Revision ID: 13904ed43b39
Revises: 7f08637fefa3
Create Date: 2025-07-15 21:37:37.159899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13904ed43b39'
down_revision = '7f08637fefa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server', sa.String(length=128), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('login', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('sender', sa.String(length=128), nullable=True),
    sa.Column('registration_template', sa.Text(), nullable=True),
    sa.Column('cancellation_template', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_settings')
    # ### end Alembic commands ###
