"""add is_deleted flag

Revision ID: 4299368c4dd9
Revises: 13904ed43b39
Create Date: 2025-07-15 22:18:57.503722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4299368c4dd9'
down_revision = '13904ed43b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_deleted',
                sa.Boolean(),
                nullable=False,
                server_default='0',
            ),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
