"""add email column

Revision ID: eb0ac69d8f6c
Revises: 6ef85ec0c835
Create Date: 2025-07-15 16:35:52.120158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0ac69d8f6c'
down_revision = '6ef85ec0c835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('email', sa.String(length=128), nullable=False)
        )
        batch_op.create_unique_constraint('uq_volunteers_email', ['email'])
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False)
        )
        batch_op.drop_constraint('uq_volunteers_email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
